mediapipe:
  min_detection_confidence: 0.5
  max_num_hands: 1

general:
  seed: 42
  split_ratios:
    train: 0.7
    val: 0.15
    test: 0.15

dataset:
  repo: "debashishsau/aslamerican-sign-language-aplhabet-dataset"
  num_instances_per_sign: 6800